### ISSUE TITLE
Create a redirect URL for jersey orders

### ISSUE THREAD

**Issue by hugodahl** [livecoders/website#108]
[As mentioned on Discord](https://discordapp.com/channels/557618010261684224/654826569151414282/729820071723270154), giving the jerseys a permanent link that redirects to the shop page to make it easier to remember and share. As @csharpfritz mentioned, making it an entry in the `netlify.toml` page would make the most sense, such as "jerseys.livecoders.dev". 

There is one caveat I wanted to check about and discuss first, however. An HTTP 301 is a permanent redirect. Per the spec, browsers MAY cache this response and avoid a DNS lookup for later requests. Will the link for jersey orders remain the same year to year? I presume that the plan is to stick with Custom eSports barring anything unforeseen, in which case, all aboard! 

However, if they decide to change their URL structure at some point, and don't add the 301 redirect on their end, I'm not sure how browsers would handle a permanent redirect to an HTTP 404 page, or even HTTP 310 (Gone).

Thoughts?

**Comment by csharpfritz** [comment]
Let's revisit this, as we do have a complete store available with both 2019 and 2020 jerseys at:  https://customesports.com/product-category/team-store/the-live-coders/

**Comment by csharpfritz** [comment]
It looks like there might be one more step to get this working...  I'll investigate the Netlify account

**Comment by ThindalTV** [comment]
I don't think this issue is relevant at the moment. We can revisit this if/when there's renewed interest in LC swag.
