### ISSUE TITLE
Automate creating member pages

### ISSUE THREAD

**Issue by lannonbr** [livecoders/website#16]
There is a NodeJS script at https://github.com/livecoders/website/tree/master/scripts/genMembers which will generate new member pages on the fly so we just need to hook it up to GitHub Actions and then set it on a schedule to occasionally generate pages as we add new members over time.

**Comment by csharpfritz** [comment]
This was working great until the oauth change in the Twitch API last week. 

Let’s add that header and re-activate the action.
