### ISSUE TITLE
Member pages

### ISSUE THREAD

**Issue by lannonbr** [livecoders/website#2]
It would be nice to have a single page for each member of the Live Coders to promote their stream and brand.

This also could include:

- content about what they do on stream
- regular stream times
- social media links
- links to personal sites / blogs

**Comment by lannonbr** [comment]
With this, I think it would be useful to have all of these pages just be written in markdown so each member doesn't need to be a web developer to add their page. This also could allow for consistency of style across the site for all members

**Comment by LuckyNoS7evin** [comment]
Maybe use Gridsome/Gatsby GQL to maybe allow for adding timeline feeds in? 

Github Activity, dev.to, medium, other blog feed... so it's just simple items, maybe also a stream feed, so a started streaming activity is posted to that feed for example

**Comment by lannonbr** [comment]
This is done for the MVP. Each member has a markdown file they can edit in in `src/members`
