### ISSUE TITLE
Add more prominent Twitch Team page link 

### ISSUE THREAD

**Issue by lannonbr** [livecoders/website#23]
@talk2MeGooseman commented that it's not blatant on how to get to the Twitch Team page, so it may be good to place it somewhere on the site (maybe like the main nav)

**Comment by mtheoryx** [comment]
I'll just start out a PR to see how you all like the idea. Add a link in the header nav and the footer that goes off site to the page.

Someone better might look at whether we should spice up the link color, style, hover, icon whatever ya want :)
