### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by lannonbr** [livecoders/website#3]
We should figure out a tech stack for the site. If you have an idea for a stack that could be useful, make a comment below and try to have pros & cons for why that would be a good choice. If you like a stack already suggested, give it a 👍

**Comment by lannonbr** [comment]
For my recommendation, I am leaning towards Gatsby as a framework.

Pros:
- Static site: Can be hosted anywhere (Azure, AWS, Nginx, Netlify, etc)
- Content with Markdown: We can generate the main content pages using markdown so then if someone does not know React, they don't have to ramp up to make meaningful contributions to the site.
- Performance out of the box: It provides features like preloading pages using IntersectionObserver and performant images with lazy loading and [srcset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) so if you load the site on a mobile device, a high-res image may not needed to be loaded with the smaller screens.

Cons:
- Not everyone may know React or GraphQL. This could be offset as there are people on the team who use React and/or Gatsby and could be brought in as domain experts.

**Comment by RamblingGeekUK** [comment]
This all sounds really good with me, I really like the Markdown idea.

**Comment by tscholze** [comment]
Great idea with Markdown. The question is, if we / you need a big framework like Gatsby.
Maybe we can use as a more lightweight static site generator like [Jekyll](https://jekyllrb.com). This would allow us to use for example GitHub pages with zero costs as a hosting platform.

If the site contains any more or less dynamic information (Streamer online status, etc. pp), we could use Azure functions or Firebase functions to update the markdown and push them into the GitHub site repository.

**Comment by lannonbr** [comment]
The site has been developed with Gatsby. For now it isn't ingesting dynamic data but will in the near future
