### ISSUE TITLE
Home Page Image of Team Members Upside down on some browsers

### ISSUE THREAD

**Issue by MaryJoStaebler** [livecoders/website#41]
On an iPad (at least), the photo of live coders in the second section is upside down.   Some in stream chats have seen it as well.  I've only seen it on the iPad.

**Comment by lannonbr** [comment]
Yeah this is I believe something to do with the EXIF data of the image that only impacts iOS devices. I don't have a direct solution to it at the moment but I will look into it

**Comment by garethhubball** [comment]
Reproduced in Microsoft Edge Version 81.0.416.41 (Official build) beta (64-bit) on my computer.

**Comment by SanaRinomi** [comment]
Reproduced in Firefox Developer Edition 76.0b5 (64-bit) on a Windows 10 machine.

**Comment by SanaRinomi** [comment]
Extracting metadata from the image. It has an `Orientation` tag set to `bottom right`.
![image](https://user-images.githubusercontent.com/16209282/79693924-b6508d80-826d-11ea-86e5-9a2b747ea87a.png)

Here's a normal image in comparison:
![image](https://user-images.githubusercontent.com/16209282/79693940-d3855c00-826d-11ea-8fbf-16fb5fea0fd1.png)
