### ISSUE TITLE
Filtering & Searching on Team Members Listing

### ISSUE THREAD

**Issue by lannonbr** [livecoders/website#5]
Have the ability to either search by name for streamers on the team or filter down by categories (Programming Languages, Technology, Category, Spoken Language, etc)

**Comment by SanaRinomi** [comment]
Standardized categories? I'm saying as many have different ways of adding JavaScript as a tag for example, and to aid in that users finding what they want.

Apart from that, maybe adding `#` in search to filter by tags/categories?

**Comment by lannonbr** [comment]
Yeah the plan was for the tags to be a free-for-all to start and then I will try culling things down once a good portion of the team has their content on the site.

**Comment by aheil** [comment]
My chat recommended this feature today. 
Filtering for tags would be a great enhancement. 
Would be fine if typing a nonexisting tag, that no entries are shown.
