### ISSUE TITLE
Add StackOverflow to member profile links

### ISSUE THREAD

**Issue by nicolaiparlog** [livecoders/website#81]
Some users may be active on StackOverflow and it would be cool if they could show that off in their profile page.

If I didn't miss anything, a frontmatter entry like this should do:

```
stackoverflow-id: 2525313
```

Translates to `https://stackoverflow.com/users/${stackoverflow-id}`.

**Comment by mtheoryx** [comment]
Great idea! Would you mind adding a user id for testing, if you have one and don't mind?

**Comment by nicolaiparlog** [comment]
Thank you @lannonbr! :+1:
