### ISSUE TITLE
Archive List of Past Speakers

### ISSUE THREAD

**Issue by chances** [livecoders/website#85]
The [Speakers](https://captcalli.github.io/LiveCodersConf/#speakers) page on the website is now empty? Where can we find a list of past talks and speakers from the April 9th conference?

**Past speakers should be archived on the website, following the lead of most other conference websites.**

For example, [GitMerge 2020](https://git-merge.com/#speakers)

**Comment by mtheoryx** [comment]
That's a fantastic idea, I also like being able to see past conference speakers.

However, this repo is not for that conference website. Here is where you'd want to open an issue for that one:

https://github.com/CaptCalli/LiveCodersConf
